[package]
name = "nextest-cache"
description = "Reference result-cache wrapper for nextest"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
atomicwrites.workspace = true
camino-tempfile.workspace = true
clap.workspace = true
etcetera.workspace = true
hex.workspace = true
nextest-workspace-hack.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
xxhash-rust.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[dev-dependencies]
