[package]
name = "nextest-cache"
description = "Reference cache-provider wrapper for nextest"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
rust-version.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
atomicwrites.workspace = true
etcetera.workspace = true
hex.workspace = true
camino.workspace = true
nextest-runner.workspace = true
nextest-workspace-hack.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
camino-tempfile.workspace = true
